# Core
db:
    redis:
        emulate: true
        namespace: EG

# plugins:
# express-gateway-plugin-example:
#   param1: 'param from system.config'
plugins:
    jwt-policy:
        package: "./manifest.js"

middlewares:
    cors:
        action:
            origin: "http://localhost:5000" # React 클라이언트 URL
            credentials: true
# plugins:
#     proxy-with-body:
#         package: ../lib/plugins/proxy-with-body/index.js
# crypto:
#     cipherKey: sensitiveKey
#     algorithm: rs256
#     saltRounds: 10

# OAuth2 Settings
# session:
#     secret: keyboard cat
#     resave: false
#     saveUninitialized: false
# accessTokens:
#     timeToExpiry: 7200000
# refreshTokens:
#     timeToExpiry: 7200000
# authorizationCodes:
#     timeToExpiry: 300000
