http:
    port: 5001
admin:
    port: 9876
    host: localhost
apiEndpoints:
    host: localhost
    paths:
        - /auth/*
        - /board/*
serviceEndpoints:
    auth:
        url: "http://localhost:5002"
    board:
        url: "http://localhost:5003"

policies:
    - basic-auth
    - cors
    - expression
    - key-auth
    - log
    - oauth2
    - proxy
    - rate-limit
    - jwt
pipelines:
