http:
    port: 5000
admin:
    port: 9876
    host: localhost
apiEndpoints:
    api:
        host: localhost
        paths: "/ip"
serviceEndpoints:
    httpbin:
        url: "https://httpbin.org"
policies:
    - basic-auth
    - cors
    - expression
    - key-auth
    - log
    - oauth2
    - proxy
    - rate-limit
pipelines:
    - name: ej
      apiEndpoints:
          - api
      policies:
          - key-auth:
          - proxy:
                action:
                    serviceEndpoint: httpbin
                    changeOrigin: true
